services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    networks:
      - proxy
    environment:
     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
networks:
   proxy: