services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    networks:
      - cloudflared
    environment:
     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run

networks:
   cloudflared:
      external: true