services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest-alpine
    restart: unless-stopped
    networks:
      - cloudflared
    ports:
      - 80:80
    volumes:
      - vaultwarden:/data

volumes:
  vaultwarden:

networks:
   cloudflared:
      external: true